### ISSUE TITLE
Please update new api from google

### ISSUE THREAD

**Issue by nk-cuongqv** [Kubessandra/react-google-calendar-api#103]
I have a mail from google like this:
One or more of your web applications uses the legacy Google Sign-In JavaScript library. Please migrate your project(s) to the new Google Identity Services SDK before March 31, 2023.
Hello Google Developer,

You are receiving this message as a reminder that one or more of your web applications uses the legacy Google Sign-In web solution. Our announced plan stated that support for the Google Sign-In JavaScript platform library will be deprecated after March 31, 2023. Additionally, we would like to apologize for any impact this change may have on your organization, and we will do our best to support you through this transition.

Please know that the legacy library will still be available for download by existing clients. A sunset date, after which the legacy library will no longer be available for use, will be communicated in the future.

What do I need to know?
To help you find out which of your web apps or environments are affected, we’re sharing a list of your client ID(s) that use the legacy Google Sign-In web solution. This list should help you evaluate user impact and prioritize the migration work more efficiently. If you have Google Cloud Platform (GCP) console login issues, Google Cloud Support can help you. Please file a ticket with the Support Hub.

App Name	Client ID
ワークレビューDX by GMO
What do I need to do?
After March 31, 2023, migration to Google Identity Services is recommended to sign in customers using their Google Account to your platform. The SDK will use the new Sign in with Google client library. In addition to prior authentication and authorization functionality, this new Sign in with Google library also offers an improved user experience that increases data sharing transparency and decreases sign-in friction.

Please migrate to the new Google Identity Services by following guides for authorization and authentication. If you have migration-specific feedback to share, send an email to gis-migration-feedback@google.com.

We thank you for your patience and understanding as we make this important change.

–The Google Identity Services Team

**Comment by nk-cuongqv** [comment]
its change api from:
https://developers.google.com/identity/sign-in/web/sign-in?hl=ja
to:
https://developers.google.com/identity/gsi/web/guides/overview?hl=ja

**Comment by OchotaDariusz** [comment]
@nk-cuongqv i've saw your issue and i wanted to try help you 😄. Look:
> Please know that the legacy library will still be available for download by existing clients. A sunset date, after which the legacy library will no longer be available for use, will be communicated in the future.

and
> After March 31, 2023, migration to Google Identity Services is recommended ...

So you don't have to worry so much, because your app will still work after 31 March. It's a recommendation not MUST-DO. And you have many time to migrate to new GIS, and if you won't do that - You will for sure meet problems with some limitations, due to old SDK.

**Comment by nk-cuongqv** [comment]
> @nk-cuongqv i've saw your issue and i wanted to try help you 😄. Look:
> 
> > Please know that the legacy library will still be available for download by existing clients. A sunset date, after which the legacy library will no longer be available for use, will be communicated in the future.
> 
> and
> 
> > After March 31, 2023, migration to Google Identity Services is recommended ...
> 
> So you don't have to worry so much, because your app will still work after 31 March. It's a recommendation not MUST-DO. And you have many time to migrate to new GIS, and if you won't do that - You will for sure meet problems with some limitations, due to old SDK.

thank you <3

**Comment by Kubessandra** [comment]
Which version of the package are you using ?
In [this](https://github.com/Kubessandra/react-google-calendar-api/commit/1a28b616da788bde8fa8ad78e43e733233c3b06b) commit, we made a migration to the new OAuth2 auth.

**Comment by nk-cuongqv** [comment]
im using version ^1.5.2. What version do i have to update? thank you!

**Comment by Kubessandra** [comment]
Version ^2.2.2 😉

**Comment by nk-cuongqv** [comment]
thank you <3
