### ISSUE TITLE
ApiCalendar has type `any`

### ISSUE THREAD

**Issue by Yathi** [Kubessandra/react-google-calendar-api#28]
When trying to import the API Calendar using `import ApiCalendar from 'react-google-calendar-api/ApiCalendar';`, I get the following error: 

```
Variable 'ApiCalendar' implicitly has type 'any' in some locations where its type cannot be determined. ts(7034)
```

I am trying to use the DoubleButton from the example.

**Comment by Insomniiak** [comment]
Is this working with this import?:
```import ApiCalendar from 'react-google-calendar-api';```

**Comment by Kubessandra** [comment]
No response since a long time I'm closing the issue, contact me again if you got another problem.

**Comment by shivamvermadev** [comment]
Both the imports from the example given on npmjs not working
