### ISSUE TITLE
How do you pass in optional query parameters like sendUpdates?

### ISSUE THREAD

**Issue by sudhamab** [Kubessandra/react-google-calendar-api#29]
hi, as per the docs [https://developers.google.com/calendar/v3/reference/events/insert](url)
in order to notify the guests through email, you can use the sendUpdates parameter. 

How does one pass that in react-google-calendar-api ? 

The invitees are not receiving an email at the moment. 

You can see an example here [https://developers.google.com/calendar/v3/reference/events/insert?apix=true#try-it](url)

I tried passing the event as the following with appropriate values for start and end time ( NOT empty as shown below )  
```
{
      "sendUpdates": "all",
      "resource": {
        "end": {},
        "start": {}
      }
}
```

but that gave a 400 error saying 'end time not found' 

If I just pass an object like 

```
var event = {
   'start' : {},
   'end' : {}
}
```

Again, with appropriate values of start and end time with datetime and timezone, it works

What am i missing?

**Comment by Insomniiak** [comment]
Hi,
You can try:
```
var event = {
 "sendUpdates":"all,
 "start": {},
 "end": {},
}
```

But I'm not sure if it will work, I maybe need to make a PR
For adding metadata

**Comment by sudhamab** [comment]
thanks. yes. you will need to add it from what i understand.

**Comment by Kubessandra** [comment]
Yes..
And nowadays it will be very hard for me to find times right now, if you want to add it and make a PR it would be awesome!

**Comment by sudhamab** [comment]
thanks @Kubessandra  will try. By the way, would you have any idea how to make this run inside an electron app? 
the `this.gapi.client.init(Config)` does not seem to get called and hence `this.gapi.auth2.getAuthInstance()`
seems to be null. 
may be accessing the window variable is not something you can do in electron. 

Would be grateful if you can point me to any resource.

**Comment by Kubessandra** [comment]
https://stackoverflow.com/questions/30681639/how-to-access-browserwindow-javascript-global-from-main-process-in-electron

Its really specific to electron so it will be hard I think

**Comment by Kubessandra** [comment]
But I can do the sendUpdates if you really need it
