### ISSUE TITLE
Patch and Update methods are not included for an existing event

### ISSUE THREAD

**Issue by PiyushJainQA** [Kubessandra/react-google-calendar-api#35]
I am trying to add a conference to an existing event using the patch() method of an event.
As of now the ApiCalendar class only contains createEvent and createEventFromNow.

Plz add patch and update methods for events.

**Comment by Kubessandra** [comment]
Hi,
Sorry but this week I'm really busy, but if you want to contribute you are welcome
If I find some time I will implement it.

**Comment by PiyushJainQA** [comment]
@Kubessandra Raised a PR, have a review, Added the function for updating the event's details.
The hangout meet can be added to an event only after the event is inserted, hence this method is mandatory to create hangout meets in any event.

**Comment by Kubessandra** [comment]
Thanks for the PR, already in Review.
Waiting for some changes and we are good to go
