### ISSUE TITLE
this.gapi not loaded

### ISSUE THREAD

**Issue by Mayank8290** [Kubessandra/react-google-calendar-api#38]
I am getting error while trying to ApiCalendar.handleAuthClick() 
 Error: this.gapi not loaded

**Comment by Kubessandra** [comment]
Maybe this will help a bit: #31

**Comment by Mayank8290** [comment]
I can't find the onload method , i have a button when the user clicks on this it will call handleAuthClick function, I clicked that button after 5 minutes but still, the same error gapi not loaded.

**Comment by Mayank8290** [comment]
i am using react native 0.61.5

**Comment by Kubessandra** [comment]
### onLoad:

```javascript
    /**
     * Execute the callback function when gapi is loaded (gapi needs to be loaded to use any other methods)
     * @param callback
     */
    public onLoad(callback: any): void
```

**Comment by Mayank8290** [comment]
The onload has never happened I have waited for 1 hour, it's nor loading, I think there is some problem . 

ApiCalendar.onLoad(() => {
            console.log("inside onload");
            //ApiCalendar.listenSign();
        });

**Comment by Kubessandra** [comment]
Sorry didn't saw your reply,
I never tried on react-native actually
