### ISSUE TITLE
Repeat created event

### ISSUE THREAD

**Issue by JulesImmerzeel** [Kubessandra/react-google-calendar-api#47]
The google calendar api gives you the option to repeat events daily weekly etc. I did not see this implementation in you your documentation or did I miss something?

**Comment by caiquejjx** [comment]
U just need to add the recurrecne property to the event object, like that: 
`await ApiCalendar.createEvent({
            summary: formData.description,
            start: { dateTime: payload.start, timeZone: 'America/Sao_Paulo' },
            end: { dateTime: payload.end, timeZone: 'America/Sao_Paulo' },
            recurrence: ['RRULE:FREQ=DAILY;COUNT=3'],
          });`
