### ISSUE TITLE
Min time as parameter passing to method and set by a user

### ISSUE THREAD

**Issue by Seibeaaar** [Kubessandra/react-google-calendar-api#50]
In listUpcominEvents timeMin param is set to today's date, but what to do when user wants to fetch past events? For that we can pass time param set by user to that method.

**Comment by Kubessandra** [comment]
Hi @Seibeaaar,
For that you can use the `listEvents` method [here](https://github.com/Kubessandra/react-google-calendar-api/blob/master/src/ApiCalendar.ts#L172)
