### ISSUE TITLE
Add new features getBasicProfile, get and Delete and improve event createEventFromNow

### ISSUE THREAD

**Issue by bateradt** [Kubessandra/react-google-calendar-api#52]
Hello everyone, first of all thanks for this library being very useful and helping me a lot.

I need to add new events to this library, I will do a PR with the new features below:

getBasicProfile () - https://developers.google.com/identity/sign-in/web/reference#googleusergetbasicprofile
get () - https://developers.google.com/calendar/v3/reference/events/get
delete () - https://developers.google.com/calendar/v3/reference/events/delete

I saw that some resources above have a PR, but were never closed, so basically I merged these changes with my branch and added just getBasicProfile.

I hope this helps the community

Thank you.

**Comment by ryokochang** [comment]
Thank you

if you need any help, im free to help!

**Comment by bateradt** [comment]
> Thank you
> 
> if you need any help, im free to help!

Can you review the PR please?

**Comment by Kubessandra** [comment]
I will review the PR tomorrow, thank you !

**Comment by bateradt** [comment]
@Kubessandra Thank you for your time. I fixed the conflicts but the Travis CI given an error:

"/home/travis/.travis/functions: line 109: ./.testEnv.sh: Permission denied
The command "./.testEnv.sh" failed and exited with 126 during ."

**Comment by ryokochang** [comment]
Check if the file has the same permissions as before

i found this about a error like this:

https://stackoverflow.com/questions/53253207/travis-tests-fail-due-to-permission-denied-on-sh-file-in-docker

**Comment by bateradt** [comment]
@ryokochang Thank you man, it's works fine using this link: 
https://stackoverflow.com/questions/42154912/permission-denied-for-build-sh-file

Tks!
