### ISSUE TITLE
[CustomList] Mehtod to list events using input custom options

### ISSUE THREAD

**Issue by clariceabreu** [Kubessandra/react-google-calendar-api#56]
Besides `listUpcomingEvents` it would be nice to have a method `listEvents` that receive the list query options as parameter, enabling custom fetches.
The method could be like that:
```
/**
   * List all events in the calendar queried by custom query options
   * See all available options here https://developers.google.com/calendar/v3/reference/events/list
   * @param {object} queryOptions to see
   * @param {string} calendarId to see by default use the calendar attribute
   * @returns {any}
   */
  public listEvents(
    queryOptions: object,
    calendarId: string = this.calendar
  ): any {
    if (this.gapi) {
      return this.gapi.client.calendar.events.list({
        calendarId,
        ...queryOptions
      });
    } else {
      console.log('Error: this.gapi not loaded');
      return false;
    }
  }
```

**Comment by clariceabreu** [comment]
I'm trying to open a PR to solve this issue, but I'm receiving 403 when trying to push the branch (it starts from `development` branch)

```
remote: Permission to Kubessandra/react-google-calendar-api.git denied to clariceabreu.
fatal: unable to access 'https://github.com/Kubessandra/react-google-calendar-api.git/': The requested URL returned error: 403
```

Can you please give me access to contribute?

**Comment by bateradt** [comment]
Hello @clariceabreu did you make a fork for this repository? I'm thinking that you trying to commit direct in the official repository, try to fallow this article below.

https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/
https://www.digitalocean.com/community/tutorials/como-criar-um-pull-request-no-github-pt

**Comment by clariceabreu** [comment]
That's true
Sorry that's my first time contributing to a project and I only read the CONTRIBUTING.md file in this project. 
I didn't know I had to make a fork
Thanks for the answer!

**Comment by clariceabreu** [comment]
@bateradt can you review my PR please? 
https://github.com/Kubessandra/react-google-calendar-api/pull/57

**Comment by bateradt** [comment]
I will review tomorrow morning.

**Comment by Kubessandra** [comment]
The PR is now merge thank you !
The version for the function is 1.3.1.

I will close this issue
