### ISSUE TITLE
Question：react_google_calendar_api__WEBPACK_IMPORTED_MODULE_8___default.a.getBasicUserProfile is not a function

### ISSUE THREAD

**Issue by k8m-git** [Kubessandra/react-google-calendar-api#60]
Hi, 

i want to get email with getBasicProfile but i`m failing to get email

```
import ApiCalendar from 'react-google-calendar-api';

const response = await ApiCalendar.getBasicUserProfile();
console.log("response is:", response.getEmail());
```

How i fix?

**Comment by bateradt** [comment]
Hello,

Try this:

const email = ApiCalendar.getBasicUserProfile().getEmail();
console.log("Email:", email);

Marcelo Fernando Scarpim
Full Stack Developer / Scrum Master
*Github : https://github.com/bateradt <https://github.com/bateradt>*
*Linkedin: https://www.linkedin.com/in/marcelo-fernando-scarpim/
<https://www.linkedin.com/in/marcelo-fernando-scarpim/>*


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

koki ***@***.***> escreveu no dia quinta, 11/03/2021 à(s)
05:46:

**Comment by k8m-git** [comment]
@bateradt 

It works!
Thanks for your help
