### ISSUE TITLE
Build parse error

### ISSUE THREAD

**Issue by ryokochang** [Kubessandra/react-google-calendar-api#61]
Eslint error on build/Apicalendar.js

Module parse failed: Unexpected token (199:16)                         
You may need an appropriate loader to handle this file type.           
             return this.gapi.client.calendar.events.list({           
                 'calendarId': calendarId,                            
                 ...queryOptions                                      
             });                                                      
         } else {  

you solved this issue on src files

**Comment by ryokochang** [comment]
i already tried remove build folder and all node modules and install, but without success

**Comment by ryokochang** [comment]
when i install the packages, it comes with build folder

**Comment by Kubessandra** [comment]
Oh sorry, I thought you were developing on the package not using it.
Is this our eslint or the eslint of the package throwing the error?

**Comment by ryokochang** [comment]
eslint of the package

**Comment by ryokochang** [comment]
i can fix this, if you want

**Comment by Kubessandra** [comment]
There is no eslint in the package.
You need to ignore the node_modules in your eslint config.

**Comment by ryokochang** [comment]
this occurs when i try to deploy my code... i cant build the project

Creating an optimized production build...
Failed to compile.
./node_modules/react-google-calendar-api/build/ApiCalendar.js
Module parse failed: Unexpected token (199:16)
You may need an appropriate loader to handle this file type.
|             return this.gapi.client.calendar.events.list({
|                 'calendarId': calendarId,
|                 ...queryOptions
|             });
|         } else {

**Comment by ryokochang** [comment]
my project still dont building

**Comment by ryokochang** [comment]
14:16 $ yarn run build
yarn run v1.22.5
$ react-app-rewired build
Creating an optimized production build...
Failed to compile.

./node_modules/react-google-calendar-api/build/ApiCalendar.js
Module parse failed: Unexpected token (199:16)
You may need an appropriate loader to handle this file type.
|             return this.gapi.client.calendar.events.list({
|                 'calendarId': calendarId,
|                 ...queryOptions
|             });
|         } else {


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Kubessandra** [comment]
How do you import the package?
