### ISSUE TITLE
 ApiCalendar.handleAuthClick() returns undefined

### ISSUE THREAD

**Issue by zohrefarzam** [Kubessandra/react-google-calendar-api#73]
hello thanks for your great work
i was using this library almost 3 month ago and it worked fine but now when i want to use it i canstantlly get this error
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'getAuthInstance')

if anyone can help me that would be great

**Comment by Kubessandra** [comment]
Hello, could you show me your code ?

**Comment by mauryabip** [comment]
TypeError: undefined is not an object (evaluating 'react_google_calendar_api__WEBPACK_IMPORTED_MODULE_2___default.a.handleAuthClick().then')

Code: 

ApiCalendar.handleAuthClick()
      .then(() => {
        console.log('sign in succesful!');
      })
      .catch((e) => {
        console.error(`sign in failed ${e}`);
      })

**Comment by Kubessandra** [comment]
Hello,
Before the v1.5.0, handleAuthClick was not returning a promise, if you upgrade the package to 1.5.0 does it solve your issue ?
`npm install --save react-google-calendar-api@latest`

**Comment by mourrrya** [comment]
Hello @Kubessandra ,
Before the v1.5.0, handleAuthClick was not returning a promise,

**Comment by Kubessandra** [comment]
I will try to check this today, normaly tonight the build will be up and running.

**Comment by Kubessandra** [comment]
The build for the js file was incorrect I just pushed a new version `v1.5.1` you can try this version normally everything will be good.

**Comment by mauryabip** [comment]
After v1.5.1

Failed to compile
./components/Main/CalendarsPage/NewCalendar.js:6
Module not found: Can't resolve 'react-google-calendar-api'
 
> 6 | import ApiCalendar from 'react-google-calendar-api';

**Comment by Kubessandra** [comment]
Thanks, will look into this tonight.

**Comment by Kubessandra** [comment]
@mauryabip normally fixed with the v1.5.2, missplacement of the import
