### ISSUE TITLE
handleAuthClick() returns undefined

### ISSUE THREAD

**Issue by geminismille** [Kubessandra/react-google-calendar-api#74]
I am using this package to integrate google calendar into one of my project and when I call `ApiCalendar.handleAuthClick()` and try to see the response it gives me undefined.

Here is the code I am doing right now:
`ApiCalendar.handleAuthClick().then((response) => {
     console.log(response);
})`

Seems like it does not send promise as a response if that is the case then how can I get the access token?

**Comment by Kubessandra** [comment]
Hello,
I will merge this PR #69 today, before this PR the handleAuthClick does not return a Promise.

**Comment by Kubessandra** [comment]
The new version is 1.5.0 and you have access to the promise
