### ISSUE TITLE
Is it safe to add google creds in the frontend.

### ISSUE THREAD

**Issue by echosonusharma** [Kubessandra/react-google-calendar-api#75]
its unsafe to add all those google creds in the frontend right. i wanted to know how bad it could get if these details gets into someone else's hand.

**Comment by Kubessandra** [comment]
```
{
  "clientId": "<CLIENT_ID>",
  "apiKey": "<API_KEY>",
  "scope": "https://www.googleapis.com/auth/calendar",
  "discoveryDocs": [
    "https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest"
  ]
}
```
If you are speaking about these.
They are not credentials and nothing secret.

**Comment by echosonusharma** [comment]
> ```
> {
>   "clientId": "<CLIENT_ID>",
>   "apiKey": "<API_KEY>",
>   "scope": "https://www.googleapis.com/auth/calendar",
>   "discoveryDocs": [
>     "https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest"
>   ]
> }
> ```
> 
> If you are speaking about these. They are not credentials and nothing secret.

anyone can take those values and use them right and its on your google dev account. thanks for the reply ☺
