### ISSUE TITLE
Migrate to Google Identity Services

### ISSUE THREAD

**Issue by justinyeung** [Kubessandra/react-google-calendar-api#77]
Google is deprecating a lot of the code used in this library. This code will not be usable for people who are starting new projects and is only usable for one more year for existing projects. I used this link (https://developers.google.com/identity/oauth2/web/guides/migration-to-gis#gis-and-gapi) to migrate my current app over (I don't use your library), and wanted to address this issue here in case anyone runs in to this issue

Here is the email I received below:

You are receiving this message because one or more of your web applications uses the [legacy Google Sign-In web solution](https://notifications.google.com/g/p/AD-FnEzt87Cjy6Ra6kDKKcOeLLrj9A02-i-MBf0fivSeOA6Mo6z_Hf8rwB80Auauyab-P-gnQrP_fD8jNiLTFQC5emz9lZ4g0ocwAfP-MtKLuAnyma3E_F83JIGvrwBPdGk). 

Our [announced plan](https://notifications.google.com/g/p/AD-FnEyLmw44MmLzLvXCqr6CJ1_5crWidHttKXWzTnKKrrl6sanr3nuyuBw558KOfiKnjUVVfz7Z_k65_ZLYrGtNbu86VSOzhBVbVp-I4Ruo0dsgAwcvH7ytR650zCFbhdcCwwp9xUT-qFNy41wqxQ) earlier this month stated that authorization support for the Google Sign-In JavaScript platform library will no longer be supported after March 31, 2023.

Beginning April 30th, 2022, new applications must use the [Google Identity Services](https://notifications.google.com/g/p/AD-FnEzu7gomox2bRX4vWhCQwYhEK-EGos0uwnR3YXiKsznT1aruTapL2BZ0HUa0SPzFsgE0UNVTz9EfJc-lmK25AHp1KQ2ACpyI5vIvmzw4wuxUSlw73ZM) library, while existing apps may continue using the Platform Library until the deprecation date.

After March 31, 2023, migration to the new Google Identity Services will be necessary to sign in customers using their Google Account to your platform. The SDK will use the new Sign In With Google client library.

**Comment by Kubessandra** [comment]
Thank you, I don't have a lot of time to update the library nowadays, but I will check if I can make the migration.

**Comment by Kubessandra** [comment]
Hi @justinyeung,
This has been fixed [commit](https://github.com/Kubessandra/react-google-calendar-api/commit/1a28b616da788bde8fa8ad78e43e733233c3b06b)

This include a lot of changes if you have any feedbacks / questions do not hesitate
