### ISSUE TITLE
HTTP Error Code 401

### ISSUE THREAD

**Issue by mado-bohsali** [Kubessandra/react-google-calendar-api#78]
Upon signing in, the popup gets closed by itself and displays: "dipframe_initialization_failed"

I am using your latest package version and OAuth credentials generated by a Google console project of mine as well as

script="https://apis.google.com/js/platform?onload=init" async defer

Kindly advise on making authentication smoother.

**Comment by Kubessandra** [comment]
I think this is not related to the package but more on the setup of your google credentials.

Here is your issue: https://stackoverflow.com/questions/46472945/idpiframe-initialization-failed-in-google-sign-in-from-localhost
