### ISSUE TITLE
This lib is not working correct anymore

### ISSUE THREAD

**Issue by noblessem** [Kubessandra/react-google-calendar-api#80]
My supposed to work 1 month ago, but now, as i understand, method ApiCalendar.handleAuthClick() is not working anymore, what i suppose to do to fix it

**Comment by noblessem** [comment]
<img width="748" alt="image" src="https://user-images.githubusercontent.com/80826132/166711327-8ac48c11-f37f-46de-a762-652255d99c66.png">

This is the error

**Comment by Kubessandra** [comment]
It was working before, did you created a new clientID?

Source: https://developers.google.com/identity/sign-in/web/reference

**Comment by noblessem** [comment]
it was working fine before, i didn`t change anyting in apiGoogleconfig.json

**Comment by noblessem** [comment]
"API keys are not supported by this API. Expected OAuth2 access token or other authentication credentials that assert a principal. See https://cloud.google.com/docs/authentication" this is the main issues. Can u tell me pls if it is working fine on ur project

**Comment by Kubessandra** [comment]
Hi @noblessem,
This has been fixed [commit](https://github.com/Kubessandra/react-google-calendar-api/commit/1a28b616da788bde8fa8ad78e43e733233c3b06b)
