### ISSUE TITLE
Gapi deprication

### ISSUE THREAD

**Issue by noblessem** [Kubessandra/react-google-calendar-api#81]
R u planning to change auth method, because from 31 march 2023 gapi is depricated, i am planning to use lib for long term, but if u r not planning to change something pls let me know

**Comment by Kubessandra** [comment]
Hi,
I'm planning to change the auth method I just still don't know when I will find the time to do it properly.

If you fill like you want to replace gapi and make a PR, I can totally help you on the PR, test it etc.

But yes my goal is to replace GAPI, fix some typescript stuff, the package is a bit old and I havn't done a big clean, so we will have a big clean / breaking changes in a few months.

**Comment by Kubessandra** [comment]
Here is the commit fixing this: [commit](https://github.com/Kubessandra/react-google-calendar-api/commit/1a28b616da788bde8fa8ad78e43e733233c3b06b)
