### ISSUE TITLE
Add conferenceData to create event

### ISSUE THREAD

**Issue by tommasini** [Kubessandra/react-google-calendar-api#91]
Awesome work!!
Writting here the suggestion to improve with add conferenceData field to createEvent method https://developers.google.com/calendar/api/guides/create-events#conferencing
https://developers.google.com/calendar/api/v3/reference/events/insert

Notice that exist a [PR](https://github.com/Kubessandra/react-google-calendar-api/pull/70) but it's from 2021

**Comment by tommasini** [comment]
Closing this issue, found a work around thanks!

**Comment by Kubessandra** [comment]
Awesome
If you can post your workaround here so if someone need it it will be easy

**Comment by tommasini** [comment]
Still trying 💪🏼

**Comment by Kubessandra** [comment]
Oh, maybe we can update the PR to make it work ?
